EcommerceApp/Models/ErrorViewModel.cs
using System;

namespace EcommerceApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EcommerceApp/Models/ProductViewModel.cs
using Ecommerce.Model;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EcommerceApp.Models
{
    public class ProductViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public int Quantity { get; set; }

        public string description { get; set; }
        public string? Image { get; set; }
        public int CategoryId { get; set; }


        public ICollection<SelectListItem> categories { get; set; }
    }
}

EcommerceApp/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ecommerce.BLL.Abstraction;
using Ecommerce.Model;
using ECommerce.Database;
using Microsoft.AspNetCore.Mvc;

namespace EcommerceApp.Controllers
{
    public class CategoryController : Controller
    {

        ICategoryManager _categoryManager;

        public CategoryController(ICategoryManager categoryManager)
        {

            _categoryManager = categoryManager;
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Category category)
        {

            _categoryManager.Add(category);

            return RedirectToAction("List");
        }

        public IActionResult List()
        {
            ICollection<Category> categories= _categoryManager.GetAll();
            return View(categories);
        }
    }
}

EcommerceApp/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ECommerce.Database;
using ECommerce.Models;
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.Controllers
{
    public class CustomerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Customer customer)
        {
            if(customer.Name != null)
            {
                CustomerDbContext db = new CustomerDbContext();
                db.Customers.Add(customer);
                db.SaveChanges();
            }
            
            return View();
        }

        public IActionResult List()
        {
            CustomerDbContext db = new CustomerDbContext();
            List<Customer> customers = db.Customers.Where(c=>c.isDeleted == false).ToList();
            return View(customers);
        }

        public IActionResult Edit(int? id)
        {
            CustomerDbContext db = new CustomerDbContext();
            Customer customer = db.Customers.Find(id);
            if (customer != null)
            {
                return View(customer);

            }
            return View();
        }

        [HttpPost]
        public IActionResult Edit(Customer customer)
        {
            CustomerDbContext db = new CustomerDbContext();
            db.Entry(customer).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            bool isSave = db.SaveChanges() > 0;
            if (isSave)
            {
                return RedirectToAction("List");

            }
            return RedirectToAction("List");
        }

        public IActionResult Delete(int? id)
        {
            CustomerDbContext db = new CustomerDbContext();
            Customer customer = db.Customers.Find(id);
            customer.isDeleted = true;
            db.Entry(customer).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            bool isSave = db.SaveChanges() > 0;
            if (isSave)
            {
                return RedirectToAction("List");

            }
            return RedirectToAction("List");
        }
    }
}

EcommerceApp/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.Controllers
{
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View("Dashboard");
        }
    }
}

EcommerceApp/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }
    }
}

EcommerceApp/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Ecommerce.BLL.Abstraction;
using Ecommerce.Model;
using EcommerceApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EcommerceApp.Controllers
{
    public class ProductController : Controller
    {
        ICategoryManager _categoryManager;
        IProductManager _productManager;
        IMapper _mapper;
        public ProductController(ICategoryManager categoryManager,IMapper mapper,IProductManager productManager)
        {
            _categoryManager = categoryManager;
            _mapper = mapper;
            _productManager = productManager;

        }
        public IActionResult Create()
        {
            ProductViewModel productViewModel = new ProductViewModel();

            productViewModel.categories = _categoryManager.GetAll().Select(
                                                                              c => new SelectListItem
                                                                              {
                                                                                  Text = c.Name,
                                                                                  Value = c.Id.ToString()

                                                                              }).ToList();

            return View(productViewModel);
        }
        [HttpPost]
        public IActionResult Create(Product product)
        {
            _productManager.Add(product);
            return RedirectToAction("List");
        }

        public IActionResult List()
        {

           ICollection<Product> products = _productManager.GetAll();
            return View(products);
        }


        public IActionResult Edit(int? id)
        {
            ProductViewModel productViewModel = new ProductViewModel();

            productViewModel.categories = _categoryManager.GetAll().Select(
                                                                              c => new SelectListItem
                                                                              {
                                                                                  Text = c.Name,
                                                                                  Value = c.Id.ToString()

                                                                              }).ToList();


            Product existingProduct = _productManager.GetById(id);
            if(existingProduct != null)
            {
                _mapper.Map<Product, ProductViewModel>(existingProduct,productViewModel);
            }
            return View(productViewModel);
        }
        [HttpPost]
        public IActionResult Edit(Product product)
        {
            bool isUpdated = _productManager.Update(product);

            if (isUpdated)
            {
                return RedirectToAction("List");
            }
            return View();
        }


    }
}

EcommerceApp/Views/Category/Create.cshtml
@{
    Layout = "_SBAdminLayout";
}

    <div class="content-wrapper">
        <div class="card">
            <div class="card-header">
                <h1 class="card-title">Add category</h1>
            </div>

            <div class="card-body">

                <form method="post">

                    <div class="form-group col-4">
                        <label for="Name">Name</label>
                        <input type="text" id="Name" name="Name" class="form-control" />
                    </div>


                    <div class="form-group col-4">

                        <input type="submit" value="Save" class="btn btn-primary">

                    </div>

                </form>



            </div>

        </div>
        </div>

EcommerceApp/Views/Category/List.cshtml
@model List<Ecommerce.Model.Category>
@{
    Layout= "_SBAdminLayout";
}

    <div class="content-wrapper">

        <div class="card">
            <h2>List</h2>

            <table class="table table-striped table-bordered table-hover table-responsive">

                <thead>
                    <tr>
                        <th>
                            Name
                        </th>

                    </tr>

                </thead>

                <tbody>

                    @foreach (var category in Model)
                    {
                        <tr>
                            <td>@category.Name</td>

                            <td>
                                <form>
                                    <button type="submit" class="btn btn-primary" asp-controller="Customer" asp-action="Edit" asp-route-id="@category.Id">Edit</button>
                                </form>
                            </td>
                            <td>
                                <form>

                                    <button type="submit" class="btn btn-danger" asp-controller="Customer" asp-action="Delete" asp-route-id="@category.Id">Delete</button>

                                </form>
                            </td>
                        </tr>

                    }



                </tbody>


            </table>
        </div>
        </div>

EcommerceApp/Views/Customer/Create.cshtml
@{
    Layout = "_SBAdminLayout";
}    

<div class="content-wrapper">

    <div class="card">
        <div class="card-header">
            <h1 class="card-title">Create Entry</h1>
        </div>

        <div class="card-body">

            <form method="post">

                <div class="form-group col-4">
                    <label for="Name">Name</label>
                    <input type="text" id="Name" name="Name" class="form-control" />
                </div>

                <div class="form-group col-4">
                    <label for="Phone">Phone</label>
                    <input type="text" id="Phone" name="MobileNumber" class="form-control" />
                </div>

                <div class="form-group col-4">
                    <label for="Address">Address</label>
                    <input type="text" id="Address" name="Address" class="form-control" />
                </div>

                <input type="submit" value="Save" class="btn btn-primary">

            </form>



        </div>

    </div>
    </div>

EcommerceApp/Views/Customer/Edit.cshtml
@model Customer
@{
    Layout = "_SBAdminLayout";
}

    <div class="content-wrapper">

        <div class="card">
            <div class="card-header">
                <h1 class="card-title">Edit Customer</h1>
            </div>

            <div class="card-body">

                <form method="post">

                    <div class="form-group">
                        <label for="Name">Name</label>
                        <input type="text" asp-for="Name" class="form-control" />
                    </div>

                    <div class="form-group">
                        <label for="Phone">Phone</label>
                        <input type="text" asp-for="MobileNumber" name="MobileNumber" class="form-control" />
                    </div>

                    <div class="form-group">
                        <label for="Address">Address</label>
                        <input type="text" asp-for="Address" class="form-control" />
                    </div>

                    <input type="submit" value="Save" asp-action="Edit" class="btn btn-primary">

                </form>



            </div>

        </div>
    </div>

EcommerceApp/Views/Customer/List.cshtml
@model List<Customer>
@{
    Layout = "_SBAdminLayout";
}

<div class="content-wrapper">

    <h2>List of Customer</h2>

    <table class="table table-striped table-bordered table-hover table-responsive">

        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Mobile Number
                </th>
                <th>
                    Address
                </th>
            </tr>

        </thead>

        <tbody>

            @foreach (var customer in Model)
            {
                <tr>
                    <td>@customer.Name</td>
                    <td>@customer.MobileNumber</td>
                    <td>@customer.Address</td>
                    <td>
                        <form>
                            <button type="submit" class="btn btn-primary" asp-controller="Customer" asp-action="Edit" asp-route-id="@customer.Id">Edit</button>
                        </form>
                    </td>
                    <td>
                        <form>

                            <button type="submit" class="btn btn-danger" asp-controller="Customer" asp-action="Delete" asp-route-id="@customer.Id">Delete</button>

                        </form>
                    </td>
                </tr>

            }



        </tbody>


    </table>
    </div>

EcommerceApp/Views/Login/Login.cshtml
@{
    Layout = null;

}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bazar.com</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="images/icons/favicon.ico" />
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/vendor/daterangepicker/daterangepicker.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/css/main.css">
    <!--===============================================================================================-->
</head>
<body>

    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <div class="login100-form-title" style="background-image: url(images/bg-01.jpg);">
                    <span class="login100-form-title-1">
                        Sign In
                    </span>
                </div>

                <form class="login100-form validate-form">
                    <div class="wrap-input100 validate-input m-b-26" data-validate="Username is required">
                        <span class="label-input100">Username</span>
                        <input class="input100" type="text" name="username" placeholder="Enter username">
                        <span class="focus-input100"></span>
                    </div>

                    <div class="wrap-input100 validate-input m-b-18" data-validate="Password is required">
                        <span class="label-input100">Password</span>
                        <input class="input100" type="password" name="pass" placeholder="Enter password">
                        <span class="focus-input100"></span>
                    </div>

                    <div class="flex-sb-m w-full p-b-30">
                        <div class="contact100-form-checkbox">
                            <input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
                            <label class="label-checkbox100" for="ckb1">
                                Remember me
                            </label>
                        </div>

                        <div>
                            <a href="#" class="txt1">
                                Forgot Password?
                            </a>
                        </div>
                    </div>

                    <div class="container-login100-form-btn">
                        <button class="login100-form-btn" asp-action="Index" asp-controller="Dashboard">
                            Login
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!--===============================================================================================-->
    <script src="~/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/vendor/animsition/js/animsition.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/vendor/bootstrap/js/popper.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/vendor/daterangepicker/moment.min.js"></script>
    <script src="~/vendor/daterangepicker/daterangepicker.js"></script>
    <!--===============================================================================================-->
    <script src="~/vendor/countdowntime/countdowntime.js"></script>
    <!--===============================================================================================-->
    <script src="~/js/main.js"></script>

</body>
</html>

EcommerceApp/Views/Product/Create.cshtml
@model EcommerceApp.Models.ProductViewModel


@{
    Layout = "_SBAdminLayout";
}
    <div class="content-wrapper">
        <div class="card">
            <div class="card-header">
                <h1 class="card-title">Product Entry</h1>
            </div>

            <div class="card-body">

                <form method="post">
                    <div class="form-group col-4">
                        <label>Category</label>
                        <select type="text" asp-for="CategoryId" asp-items="Model.categories" class="form-control">
                            <option>Select .......</option>
                        </select>
                    </div>
                    <div class="form-group col-4">
                        <label for="Name">Name</label>
                        <input type="text" asp-for="Name" class="form-control" />
                    </div>

                    <div class="form-group col-4">
                        <label for="Phone">Product Description</label>
                        <input type="text" asp-for="description" class="form-control" />
                    </div>

                    <div class="form-group col-4">
                        <label for="Address">Quantity</label>
                        <input type="number" asp-for="Quantity" class="form-control" />
                    </div>
                    <div class="form-group col-4">
                        <label for="Address">Unit price</label>
                        <input type="number" asp-for="Price" class="form-control" />
                    </div>

                    <div class="form-group col-4">
                        <label for="Address">Product Image</label>
                        <input type="file" class="form-control" />
                    </div>

                    <div class="form-group col-4">
                        <input type="submit" value="Save" class="btn btn-primary">

                    </div>

                </form>



            </div>

        </div>
        </div>

EcommerceApp/Views/Product/Edit.cshtml
@model EcommerceApp.Models.ProductViewModel

@{
    Layout = "_SBAdminLayout";
}
<div class="content-wrapper">
    <div class="card">
        <div class="card-header">
            <h1 class="card-title">Edit Product</h1>
        </div>

        <div class="card-body">

            <form method="post">
                <div class="form-group col-4">
                    <label>Category</label>
                    <select type="text" asp-for="CategoryId" asp-items="Model.categories" class="form-control">
                        <option>Select .......</option>
                    </select>
                </div>
                <div class="form-group col-4">
                    <label for="Name">Name</label>
                    <input type="text" asp-for="Name" class="form-control" />
                </div>

                <div class="form-group col-4">
                    <label for="Phone">Product Description</label>
                    <input type="text" asp-for="description" class="form-control" />
                </div>

                <div class="form-group col-4">
                    <label for="Address">Quantity</label>
                    <input type="number" asp-for="Quantity" class="form-control" />
                </div>
                <div class="form-group col-4">
                    <label for="Address">Unit price</label>
                    <input type="number" asp-for="Price" class="form-control" />
                </div>

                <div class="form-group col-4">
                    <label for="Address">Product Image</label>
                    <input type="file" class="form-control" />
                </div>

                <div class="form-group col-4">
                    <input type="submit" value="Save" class="btn btn-primary">

                </div>

            </form>



        </div>

    </div>
</div>

EcommerceApp/Views/Product/List.cshtml
@model ICollection<Ecommerce.Model.Product>
@{
    Layout = "_SBAdminLayout";
}

<h2>Product list</h2>

<div class="content-wrapper">

    <div class="card">
        <h2>Product List</h2>

        

            <table class="table table-striped table-bordered table-hover table-responsive">

                <thead>
                    <tr>
                        <th>
                            Product Name
                        </th>
                        <th>
                            Description

                        </th>
                        <th>
                            Price
                        </th>
                        <th>
                            Quantity
                        </th>
                        <th>
                            Category
                        </th>


                    </tr>

                </thead>

                <tbody>

                    @foreach (var product in Model)
                    {
                        <tr>
                            <td>@product.Name</td>


                            <td>@product.description</td>


                            <td>@product.Price</td>


                            <td>@product.Quantity</td>

                            <td>@(product.Category == null ? "N/A": product.Category.Name)</td>

                            <td>
                                <form>
                                    <button type="submit" class="btn btn-primary" asp-controller="Product" asp-action="Edit" asp-route-id="@product.Id">Edit</button>
                                </form>
                            </td>
                            <td>
                                <form>

                                    <button type="submit" class="btn btn-danger" asp-controller="Customer" asp-action="Delete" asp-route-id="@product.Id">Delete</button>

                                </form>
                            </td>
                        </tr>

                    }



                </tbody>


            </table>
    </div>
</div>